- hosts: "tag_inventorygroup_benchmarking_loadgen_{{ technology }}{{ node }}_{{ run_tag }}"
  remote_user: ubuntu
  become: yes
  vars_files:
    # change to location of var files
  tasks:
    # detect skipping due to no matching hosts found issue
    - name: Create a file to signal the playbook ran
      file:
        path: run_check
        state: touch

    - name: Update all packages
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: true

    - name: Install Java 8
      apt:
        name: default-jre
        update_cache: yes
        install_recommends: yes
        state: present

    - name: Increase file descriptor limit for root
      pam_limits:
        domain: 'root'
        limit_type: '-'
        limit_item: nofile
        value: "500000"

    - name: Increase file descriptor limit for ubuntu
      pam_limits:
        domain: 'ubuntu'
        limit_type: 'soft'
        limit_item: nofile
        value: "500000"

    - name: Increase proc limit for root
      pam_limits:
        domain: 'root'
        limit_type: '-'
        limit_item: nproc
        value: "500000"

    - name: Increase proc limit for ubuntu
      pam_limits:
        domain: 'ubuntu'
        limit_type: 'soft'
        limit_item: nproc
        value: "500000"

    - name: Enable pam_limits.so
      lineinfile:
        path: /etc/pam.d/common-session
        insertafter: EOF
        line: 'session required pam_limits.so'

    - name: Reboot the machine with all defaults
      reboot: