---
# detect skipping due to no matching hosts found issue
- name: Create a file to signal the playbook ran
  file:
    path: run_check
    state: touch

- name: set hostname
  hostname:
    name: "{{ hostname }}"

- name: Increase file descriptor limit for root
  pam_limits:
    domain: 'root'
    limit_type: '-'
    limit_item: nofile
    value: "{{ fd_limit }}"

- name: Increase file descriptor limit for ubuntu
  pam_limits:
    domain: 'ubuntu'
    limit_type: 'soft'
    limit_item: nofile
    value: "{{ fd_limit }}"

- name: Enable pam_limits.so
  lineinfile:
    path: /etc/pam.d/common-session
    insertafter: EOF
    line: 'session required pam_limits.so'

- name: Ensure the locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: set as default locale
  command: update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

- name: Update all packages
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: true

- name: Add RabbitMQ directories to /etc/environment
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - { key: "RABBITMQ_MNESIA_DIR", value: "/{{ data_volume }}/data" }
    - { key: "RABBITMQ_LOG_BASE", value: "/{{ logs_volume }}/logs" }

- name: Set quorum directory
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - { key: "RABBITMQ_QUORUM_DIR", value: "/{{ quorum_volume }}/quorum" }
  when: quorum_volume != data_volume

- name: Set IO Thread pool size
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - { key: "RABBITMQ_IO_THREAD_POOL_SIZE", value: "{{ io_thread_pool_size }}" }
  when: io_thread_pool_size|int > 0

- name: Reboot the machine with all defaults
  reboot: