{
 "title": "6 Way",
 "time": { "from": "2020-05-12T09:10:28.287Z", "to": "2020-05-12T15:14:58.547Z" },
 "templating": {
  "list": [
   {
    "name": "broker1",
    "query": "SHOW TAG VALUES FROM amqp_published WITH KEY=node"
   },
   {
    "name": "broker2",
    "query": "SHOW TAG VALUES FROM amqp_published WITH KEY=node"
   },
   {
    "name": "broker3",
    "query": "SHOW TAG VALUES FROM amqp_published WITH KEY=node"
   },
   {
    "name": "broker4",
    "query": "SHOW TAG VALUES FROM amqp_published WITH KEY=node"
   },
   {
    "name": "broker5",
    "query": "SHOW TAG VALUES FROM amqp_published WITH KEY=node"
   },
   {
    "name": "broker6",
    "query": "SHOW TAG VALUES FROM amqp_published WITH KEY=node"
   }
  ]
 },
 "panels": [
  {
   "title": "Aggregate Publish Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$broker1 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker1$/" }
     ]
    },
    {
     "alias": "$broker2 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker2$/" }
     ]
    },
    {
     "alias": "$broker3 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker3$/" }
     ]
    },
    {
     "alias": "$broker4 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker4$/" }
     ]
    },
    {
     "alias": "$broker5 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker5$/" }
     ]
    },
    {
     "alias": "$broker6 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker6$/" }
     ]
    }
   ]
  },
  {
   "title": "Aggregate Published Bytes/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$broker1 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker1$/" }
     ]
    },
    {
     "alias": "$broker2 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker2$/" }
     ]
    },
    {
     "alias": "$broker3 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker3$/" }
     ]
    },
    {
     "alias": "$broker4 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker4$/" }
     ]
    },
    {
     "alias": "$broker5 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker5$/" }
     ]
    },
    {
     "alias": "$broker6 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker6$/" }
     ]
    }
   ]
  },
  {
   "title": "Aggregate Consume Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$broker1 Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker1$/" }
     ]
    },
    {
     "alias": "$broker2 Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker2$/" }
     ]
    },
    {
     "alias": "$broker3 Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker3$/" }
     ]
    },
    {
     "alias": "$broker4 Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker4$/" }
     ]
    },
    {
     "alias": "$broker5 Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker5$/" }
     ]
    },
    {
     "alias": "$broker6 Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker6$/" }
     ]
    }
   ]
  },
  {
   "title": "Aggregate Consumed Bytes/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$broker1 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker1$/" }
     ]
    },
    {
     "alias": "$broker2 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker2$/" }
     ]
    },
    {
     "alias": "$broker3 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker3$/" }
     ]
    },
    {
     "alias": "$broker4 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker4$/" }
     ]
    },
    {
     "alias": "$broker5 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker5$/" }
     ]
    },
    {
     "alias": "$broker6 Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker6$/" }
     ]
    }
   ]
  },
  {
   "title": "$broker1 Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Latency (ms) 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.5" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker1$/" }
     ]
    },
    {
     "alias": "Latency (ms) 75th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.75" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker1$/" }
     ]
    },
    {
     "alias": "Latency (ms) 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.95" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker1$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker1$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99.9th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.999" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker1$/" }
     ]
    }
   ]
  },
  {
   "title": "$broker4 Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Latency (ms) 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.5" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker4$/" }
     ]
    },
    {
     "alias": "Latency (ms) 75th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.75" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker4$/" }
     ]
    },
    {
     "alias": "Latency (ms) 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.95" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker4$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker4$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99.9th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.999" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker4$/" }
     ]
    }
   ]
  },
  {
   "title": "$broker2 Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Latency (ms) 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.5" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker2$/" }
     ]
    },
    {
     "alias": "Latency (ms) 75th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.75" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker2$/" }
     ]
    },
    {
     "alias": "Latency (ms) 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.95" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker2$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker2$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99.9th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.999" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker2$/" }
     ]
    }
   ]
  },
  {
   "title": "$broker5 Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Latency (ms) 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.5" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker5$/" }
     ]
    },
    {
     "alias": "Latency (ms) 75th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.75" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker5$/" }
     ]
    },
    {
     "alias": "Latency (ms) 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.95" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker5$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker5$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99.9th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.999" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker5$/" }
     ]
    }
   ]
  },
  {
   "title": "$broker3 Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Latency (ms) 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.5" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker3$/" }
     ]
    },
    {
     "alias": "Latency (ms) 75th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.75" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker3$/" }
     ]
    },
    {
     "alias": "Latency (ms) 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.95" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker3$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker3$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99.9th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.999" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker3$/" }
     ]
    }
   ]
  },
  {
   "title": "$broker6 Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Latency (ms) 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.5" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker6$/" }
     ]
    },
    {
     "alias": "Latency (ms) 75th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.75" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker6$/" }
     ]
    },
    {
     "alias": "Latency (ms) 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.95" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker6$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker6$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99.9th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.999" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$broker6$/" }
     ]
    }
   ]
  },
  {
   "title": "Blocked/Unblocked Connections Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$broker1 Blocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-blocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker1$/" }
     ]
    },
    {
     "alias": "$broker1 Unblocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-unblocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker1$/" }
     ]
    },
    {
     "alias": "$broker2 Blocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-blocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker2$/" }
     ]
    },
    {
     "alias": "$broker2 Unblocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-unblocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker2$/" }
     ]
    },
    {
     "alias": "$broker3 Blocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-blocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker3$/" }
     ]
    },
    {
     "alias": "$broker3 Unblocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-unblocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker3$/" }
     ]
    },
    {
     "alias": "$broker4 Blocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-blocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker4$/" }
     ]
    },
    {
     "alias": "$broker4 Unblocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-unblocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker4$/" }
     ]
    },
    {
     "alias": "$broker5 Blocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-blocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker5$/" }
     ]
    },
    {
     "alias": "$broker5 Unblocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-unblocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker5$/" }
     ]
    },
    {
     "alias": "$broker6 Blocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-blocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker6$/" }
     ]
    },
    {
     "alias": "$broker6 Unblocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-unblocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker6$/" }
     ]
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$broker1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_queue-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker1$/" }
     ]
    },
    {
     "alias": "$broker2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_queue-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker2$/" }
     ]
    },
    {
     "alias": "$broker3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_queue-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker3$/" }
     ]
    },
    {
     "alias": "$broker4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_queue-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker4$/" }
     ]
    },
    {
     "alias": "$broker5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_queue-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker5$/" }
     ]
    },
    {
     "alias": "$broker6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_queue-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker6$/" }
     ]
    }
   ]
  },
  {
   "title": "Publisher and Consumer Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$broker1 Publisher Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker1$/" }
     ]
    },
    {
     "alias": "$broker1 Consumer Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker1$/" }
     ]
    },
    {
     "alias": "$broker2 Publisher Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker2$/" }
     ]
    },
    {
     "alias": "$broker2 Consumer Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker2$/" }
     ]
    },
    {
     "alias": "$broker3 Publisher Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker3$/" }
     ]
    },
    {
     "alias": "$broker3 Consumer Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker3$/" }
     ]
    },
    {
     "alias": "$broker4 Publisher Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker4$/" }
     ]
    },
    {
     "alias": "$broker4 Consumer Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker4$/" }
     ]
    },
    {
     "alias": "$broker5 Publisher Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker5$/" }
     ]
    },
    {
     "alias": "$broker5 Consumer Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker5$/" }
     ]
    },
    {
     "alias": "$broker6 Publisher Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker6$/" }
     ]
    },
    {
     "alias": "$broker6 Consumer Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker6$/" }
     ]
    }
   ]
  },
  {
   "title": "Target Publish Rate Per Publisher",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$broker1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_target-publish-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker1$/" }
     ]
    },
    {
     "alias": "$broker2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_target-publish-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker2$/" }
     ]
    },
    {
     "alias": "$broker3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_target-publish-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker3$/" }
     ]
    },
    {
     "alias": "$broker4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_target-publish-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker4$/" }
     ]
    },
    {
     "alias": "$broker5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_target-publish-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker5$/" }
     ]
    },
    {
     "alias": "$broker6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_target-publish-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$broker6$/" }
     ]
    }
   ]
  }
 ]
}