{
 "title": "Erlang-Distribution",
 "description": "Erlang cluster metrics",
 "tags": [ "rabbitmq-prometheus" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rabbitmq_cluster",
    "label": "RabbitMQ Cluster",
    "query": "SHOW TAG VALUES FROM \"rabbitmq_identity_info\" WITH key = \"rabbitmq_cluster\""
   },
   {
    "name": "erlang_vm_dist_proc_type",
    "label": "Process type",
    "query": "SHOW TAG VALUES FROM \"erlang_vm_dist_proc_status\" WITH key = \"type\""
   },
   {
    "name": "brokers",
    "query": "SHOW TAG VALUES FROM \"rabbitmq_identity_info\" WITH key = \"rabbitmq_node\" WHERE rabbitmq_cluster =~ /$rabbitmq_cluster/"
   },
   {
    "name": "hosts",
    "query": "SHOW TAG VALUES FROM \"rabbitmq_identity_info\" WITH key = \"rabbitmq_node\" WHERE rabbitmq_cluster =~ /$rabbitmq_cluster/"
   }
  ]
 },
 "panels": [
  {
   "title": "All distribution links",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "erlang_vm_dist_node_state",
     "query": "SELECT count(\"gauge\") FROM \"erlang_vm_dist_node_state\" WHERE (\"host\" =~ /^$hosts$/) AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "peer", "operator": "=~", "value": "/^$brokers$/" }
     ]
    }
   ]
  },
  {
   "title": "Established distribution links",
   "type": "singlestat",
   "description": "When a connection between a node and peer is established, the distribution link is considered to be `up`",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "erlang_vm_dist_node_state",
     "query": "SELECT count(\"gauge\") FROM \"erlang_vm_dist_node_state\" WHERE (\"host\" =~ /^$hosts$/ AND \"gauge\" = 3) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "field(gauge)", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Connecting distribution links",
   "type": "singlestat",
   "description": "When a new connection is exchanging information between the node and the peer the distribution link is considered to be `pending`",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"gauge\") FROM \"erlang_vm_dist_node_state\" WHERE (\"host\" =~ /^$hosts$/ AND \"gauge\" = 1) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Waiting distribution links",
   "type": "singlestat",
   "description": "When a new connection is established and there is an existing connection between the node and the peer, this connection needs to wait for the initial connection to go down before it can become active. The distribution link is considered `up_pending`",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"gauge\") FROM \"erlang_vm_dist_node_state\" WHERE (\"host\" =~ /^$hosts$/ AND \"gauge\" = 2) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "distribution links", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Data sent to peer node / s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host -> $tag_peer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "peer" ], "type": "tag" }
     ],
     "measurement": "erlang_vm_dist_send_bytes",
     "query": "SELECT non_negative_derivative(max(\"gauge\"), 1s) FROM \"erlang_vm_dist_send_bytes\" WHERE (\"host\" =~ /^$hosts$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"peer\"",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Erlang Run Queues Length",
   "type": "graph",
   "description": "Data currently buffered in the output queue of the distribution link\n\nAny values above the 64MB threshold hint to an overloaded distribution\n\nBy default, RabbitMQ sets an upper limit of 128MB for the distribution buffer\n\n* [erlang/otp#2270](https://github.com/erlang/otp/pull/2270)\n* [erl +zdbbl](http://erlang.org/doc/man/erl.html#+zdbbl)\n",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "erlang_vm_statistics_run_queues_length_total",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Data buffered in the distribution links queue",
   "type": "graph",
   "description": "Data currently buffered in the output queue of the distribution link\n\nAny values above the 64MB threshold hint to an overloaded distribution\n\nBy default, RabbitMQ sets an upper limit of 128MB for the distribution buffer\n\n* [erlang/otp#2270](https://github.com/erlang/otp/pull/2270)\n* [erl +zdbbl](http://erlang.org/doc/man/erl.html#+zdbbl)\n",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host -> $tag_peer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "peer" ], "type": "tag" }
     ],
     "measurement": "erlang_vm_dist_port_queue_size_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  { "title": "inet socket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Distribution messages sent to peer node / s",
   "type": "graph",
   "description": "Number of inet packets sent to the distribution link port.\n\nIf too few messages are sent and data sits in the port driver buffer, increasing the `inet_dist_connect_options` as well as `inet_dist_listen_options` buffer values will result in more stable throughput.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host -> $tag_peer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "peer" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "erlang_vm_dist_send_cnt",
     "query": "SELECT non_negative_derivative(max(\"gauge\"), 1s) FROM \"erlang_vm_dist_send_cnt\" WHERE (\"host\" =~ /^$hosts$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"peer\" fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Data received from peer node / s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host -> $tag_peer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "peer" ], "type": "tag" }
     ],
     "measurement": "erlang_vm_dist_recv_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Distribution messages received from peer node / s",
   "type": "graph",
   "description": "Number of inet packets sent to the distribution link port.\n\nIf too few messages are sent and data sits in the port driver buffer, increasing the `inet_dist_connect_options` as well as `inet_dist_listen_options` buffer values will result in more stable throughput.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host -> $tag_peer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "peer" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "erlang_vm_dist_recv_cnt",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  { "title": "port driver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory used by the port driver",
   "type": "graph",
   "description": "The total number of bytes allocated for this port by the runtime system. The port itself can have allocated memory that is not included.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host -> $tag_peer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "peer" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "erlang_vm_dist_port_memory_bytes",
     "query": "SELECT max(\"gauge\") FROM \"erlang_vm_dist_port_memory_bytes\" WHERE (\"host\" =~ /^$hosts$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"peer\" fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Data in the port driver buffer",
   "type": "graph",
   "description": "The total number of bytes queued by the port using the ERTS driver queue implementation\n\nAny values above a few KBs hint to an overloaded distribution",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host -> $tag_peer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"gauge\") FROM \"erlang_vm_dist_port_queue_size_bytes\" WHERE (\"host\" =~ /^$hosts$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"peer\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$erlang_vm_dist_proc_type process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "erlang_vm_dist_proc_type"
  },
  {
   "title": "Memory used by the process",
   "type": "graph",
   "description": "The size in bytes of process memory. This includes call stack, heap, and internal structures.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host -> $tag_peer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"gauge\") FROM \"erlang_vm_dist_proc_memory_bytes\" WHERE (\"host\" =~ /^$hosts$/ AND \"type\" =~ /^$erlang_vm_dist_proc_type$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"peer\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Messages in the process queue",
   "type": "graph",
   "description": "The number of messages currently in the message queue of the process\n\nAny values above 0 hint to an overloaded distribution",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host -> $tag_peer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "peer" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "erlang_vm_dist_proc_message_queue_len",
     "query": "SELECT max(\"gauge\") FROM \"erlang_vm_dist_proc_message_queue_len\" WHERE (\"host\" =~ /^$hosts$/ AND \"type\" =~ /^$erlang_vm_dist_proc_type$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"peer\" fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$erlang_vm_dist_proc_type$/" }
     ]
    }
   ]
  },
  {
   "title": "Dirty IO Schedulers Run Queue Length",
   "type": "graph",
   "description": "The length of the dirty IO scheduler run queues",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "erlang_vm_statistics_dirty_io_run_queue_length",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory used by the process",
   "type": "graph",
   "description": "The size in bytes of process memory. This includes call stack, heap, and internal structures.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host -> $tag_peer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"gauge\") FROM \"erlang_vm_dist_proc_memory_bytes\" WHERE (\"host\" =~ /^$hosts$/ AND \"type\" =~ /^$erlang_vm_dist_proc_type$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"peer\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}