{
 "title": "One Node",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "NodeA",
    "label": "Broker",
    "query": "SHOW TAG VALUES FROM amqp_published WITH KEY=node"
   }
  ]
 },
 "panels": [
  {
   "title": "Publish and Consume Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$NodeA Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$NodeA Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Published and Consumed (Body)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$NodeA Published MB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$NodeA Consumed MB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Target Publish Rate Per Publisher",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "rabbitmq$NodeA Target Publish Rate Per Publisher (msgs / sec)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_target-publish-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Latency 50th and 95 Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$NodeA (ms) 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.5" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$NodeA  (ms) 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.95" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Publisher In-Flight-Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$NodeA Publisher In-Flight-Limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-in-flight-limit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Latency 99th and 99.9th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$NodeA (ms) 99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$NodeA (ms) 99.9th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.999" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Publisher and Consumer Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$NodeA Publisher Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$NodeA Consumer Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "$NodeA Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Latency (ms) 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.5" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "Latency (ms) 75th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.75" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "Latency (ms) 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.95" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99.9th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.999" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumer Prefetch and Ack Interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$NodeA Max Consumer Prefetch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-prefetch",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$NodeA Max Consumer Ack Interval",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-ack-interval",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Confirm Latency 50th and 95th Percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$NodeA Latency(ms) 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_confirm-latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.5" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$NodeA Latency(ms) 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_confirm-latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.95" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$NodeA Queue Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_queue-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Confirm Latency 99th and 99.9th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$NodeA Latency (ms) 99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_confirm-latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$NodeA Latency (ms) 99.9th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_confirm-latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.999" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Message Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$NodeA Max Message Size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumer Connection Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$NodeA Consumer Connection Errors (Sum in interval)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-conn-errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Routing Key Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$NodeA Routing Key Length",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_routingkey-length",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Delivery Mode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$NodeA Delivery Mode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publish-msg-del-mode",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Per Consumer Rates (Fairness)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Node A Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-consumer-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "min" }
     ]
    },
    {
     "alias": "Node A 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-consumer-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "50" }
     ]
    },
    {
     "alias": "Node A 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-consumer-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "95" }
     ]
    },
    {
     "alias": "Node B Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-consumer-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "min" }
     ]
    },
    {
     "alias": "Node B 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-consumer-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "50" }
     ]
    },
    {
     "alias": "Node B 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-consumer-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "95" }
     ]
    }
   ]
  },
  {
   "title": "Message Headers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$NodeA Message Headers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-headers",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Per Publisher Rates (Fairness)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Node A Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "min" }
     ]
    },
    {
     "alias": "Node A 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "50" }
     ]
    },
    {
     "alias": "Node A 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "95" }
     ]
    },
    {
     "alias": "Node B Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "min" }
     ]
    },
    {
     "alias": "Node B 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "50" }
     ]
    },
    {
     "alias": "Node B 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "95" }
     ]
    }
   ]
  }
 ]
}