---
- name: stop rabbitmq app
  command: /rabbitmq/sbin/rabbitmqctl stop_app

- name: add this node to cluster
  command: /rabbitmq/sbin/rabbitmqctl join_cluster rabbit@{{ rabbitmq_cluster_master }}

- name: start rabbitmq app
  command: /rabbitmq/sbin/rabbitmqctl start_app