---
- name: Set default configuration
  template:
    src: rabbitmq.conf.j2
    dest: /rabbitmq/etc/rabbitmq/rabbitmq.conf
    mode: 0400
    force: true
  tags: [configuration]

- name: Set advanced raft configuration, location of wal...
  template:
    src: raft.advanced.config.j2
    dest: /rabbitmq/etc/rabbitmq/advanced.config
    mode: 0400
    force: true
  tags: [configuration]
  when: use_config == 'raft'