---
- name: Set hosts file with instance ips
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.host }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.host }}"
    # owner: root
    # group: root
    # mode: 0644
  with_items: "{{ rabbitmq_hosts }}"
  when: rabbitmq_hosts is defined

- name: Install RabbitMQ public key
  apt_key:
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    state: present

- name: Install Erlang Solutions public key
  apt_key:
    url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    state: present

- name: copy Erlang DEB file to /tmp
  copy: 
    src: "{{ local_deb_file_dir }}/{{ erlang_deb_file }}"
    dest: /tmp

- name: Install Erlang from DEB file
  apt:
    deb: "/tmp/{{ erlang_deb_file }}"

- include_tasks: install_from_deb.yml
  when: install_from == 'deb'

- include_tasks: install_from_generic.yml
  when: install_from == 'generic'
  
- include_tasks: join_cluster.yml
  when: node_role == "joinee" and install_from == 'deb'

- include_tasks: join_cluster_generic.yml
  when: node_role == "joinee" and install_from == 'generic'