create table benchmark
(
	benchmark_id uuid not null constraint benchmark_pk1 primary key,
	run_id varchar(100) not null,
	topology_name varchar(200) not null,
	benchmark_type varchar(20) not null,
	dimensions varchar(1000) not null,
	description varchar(1000) not null,
	run_tag varchar(10) not null,
	config_tag varchar(50) not null,
	node varchar(50) not null,
    technology varchar(100) not null,
	broker_version varchar(50) not null,
	instance varchar(100) not null,
	volume varchar(100) not null,
	filesystem varchar(10) not null,
	tenancy varchar(50) not null,
	core_count smallint not null,
	threads_per_core smallint not null,
	hosting varchar(50) not null,
	start_time timestamp not null,
	start_ms bigint not null,
	end_time timestamp,
	end_ms bigint
);

CREATE TABLE STEP (
    BENCHMARK_ID UUID NOT NULL,
    STEP SMALLINT NOT NULL,
    STEP_VALUE VARCHAR(200) NULL,
    DURATION_SECONDS INT NOT NULL,
    RECORDING_SECONDS INT NULL,
    SENT_COUNT BIGINT NULL,
    SENT_BYTES_COUNT BIGINT NULL,
    RECEIVE_COUNT BIGINT NULL,
    RECEIVE_BYTES_COUNT BIGINT NULL,
    LATENCY_MS_MIN FLOAT(2) NULL,
    LATENCY_MS_50 FLOAT(2) NULL,
    LATENCY_MS_75 FLOAT(2) NULL,
    LATENCY_MS_95 FLOAT(2) NULL,
    LATENCY_MS_99 FLOAT(2) NULL,
    LATENCY_MS_999 FLOAT(2) NULL,
    LATENCY_MS_MAX FLOAT(2) NULL,
    CONFIRM_LATENCY_MS_MIN FLOAT(2) NULL,
    CONFIRM_LATENCY_MS_50 FLOAT(2) NULL,
    CONFIRM_LATENCY_MS_75 FLOAT(2) NULL,
    CONFIRM_LATENCY_MS_95 FLOAT(2) NULL,
    CONFIRM_LATENCY_MS_99 FLOAT(2) NULL,
    CONFIRM_LATENCY_MS_999 FLOAT(2) NULL,
    CONFIRM_LATENCY_MS_MAX FLOAT(2) NULL,
    SEND_RATE_MIN FLOAT(2) NULL,
    SEND_RATE_AVG FLOAT(2) NULL,
    SEND_RATE_MED FLOAT(2) NULL,
    SEND_RATE_STDDEV FLOAT(2) NULL,
    SEND_RATE_MAX FLOAT(2) NULL,
    RECEIVE_RATE_MIN FLOAT(2) NULL,
    RECEIVE_RATE_AVG FLOAT(2) NULL,
    RECEIVE_RATE_MED FLOAT(2) NULL,
    RECEIVE_RATE_STDDEV FLOAT(2) NULL,
    RECEIVE_RATE_MAX FLOAT(2) NULL,
    PER_PUBLISHER_RATE_MIN FLOAT(2) NULL,
    PER_PUBLISHER_RATE_5 FLOAT(2) NULL,
    PER_PUBLISHER_RATE_25 FLOAT(2) NULL,
    PER_PUBLISHER_RATE_50 FLOAT(2) NULL,
    PER_PUBLISHER_RATE_75 FLOAT(2) NULL,
    PER_PUBLISHER_RATE_95 FLOAT(2) NULL,
    PER_PUBLISHER_RATE_MAX FLOAT(2) NULL,
    PER_CONSUMER_RATE_MIN FLOAT(2) NULL,
    PER_CONSUMER_RATE_5 FLOAT(2) NULL,
    PER_CONSUMER_RATE_25 FLOAT(2) NULL,
    PER_CONSUMER_RATE_50 FLOAT(2) NULL,
    PER_CONSUMER_RATE_75 FLOAT(2) NULL,
    PER_CONSUMER_RATE_95 FLOAT(2) NULL,
    PER_CONSUMER_RATE_MAX FLOAT(2) NULL,
    START_TIME TIMESTAMP NOT NULL,
    START_MS BIGINT NOT NULL,
    END_TIME TIMESTAMP NULL,
    END_MS BIGINT NULL,
    PRIMARY KEY(BENCHMARK_ID, STEP)
);