{
 "title": "Node A vs Node B",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "TechnologyA", "label": "Technology A", "query": "rabbitmq" },
   {
    "name": "NodeA",
    "label": "Node A",
    "query": "SHOW TAG VALUES FROM amqp_published WITH KEY=node"
   },
   { "name": "TechnologyB", "label": "Technology B", "query": "rabbitmq" },
   {
    "name": "NodeB",
    "label": "Node B",
    "query": "SHOW TAG VALUES FROM amqp_published WITH KEY=node"
   }
  ]
 },
 "panels": [
  {
   "title": "Publish and Consume Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyA $NodeA Confirmed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_confirmed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyA $NodeA Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Published",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "$TechnologyA $NodeB Confirmed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_confirmed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Published and Consumed (Body) MB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA Published MB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyA $NodeA Consumed MB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Published MB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Consumed MB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumed-msg-bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$NodeA Max Message Size Bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$NodeA Min Message Size Bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$NodeA Average Message Size Bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$NodeB Min Message Size Bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "$NodeB Average Message Size Bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "$NodeB Max Message Size Bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "$NodeA Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Latency (ms) 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.5" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "Latency (ms) 75th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.75" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "Latency (ms) 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.95" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.99" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99.9th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.999" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Consumer Ack Interval Milliseconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-ack-interval-ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-ack-interval-ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "$NodeB Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Latency (ms) 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.5" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "Latency (ms) 75th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.75" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "Latency (ms) 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.95" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.99" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "Latency (ms) 99.9th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.999" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Msgs Per Ack (multiple flag usage)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-acks-avg-msgs-per-ack",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-acks-avg-msgs-per-ack",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Publisher In-Flight-Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA Publisher In-Flight-Limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-in-flight-limit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Publisher In-Flight-Limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-in-flight-limit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumer Ack Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-acks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-acks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumer Prefetch and Ack Interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA Consumer Prefetch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-prefetch",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyA $NodeA Consumer Ack Interval",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-ack-interval",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Consumer Prefetch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-prefetch",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Consumer Ack Interval",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-ack-interval",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA Queue Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_queue-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Queue Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_queue-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Latency 50th and 95 Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA (ms) 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.5" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyA $NodeA  (ms) 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.95" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB (ms) 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.5" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB  (ms) 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.95" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Publisher and Consumer Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA Publisher Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyA $NodeA Consumer Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Publisher Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Consumer Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Latency 99th and 99.9th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA (ms) 99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.99" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyA $NodeA (ms) 99.9th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.999" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB (ms) 99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.99" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB (ms) 99.9th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.999" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Target Publish Rate Per Publisher",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA Target Publish Rate Per Publisher (msgs / sec)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_target-publish-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Target Publish Rate Per Publisher (msgs / sec)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_target-publish-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Confirm Latency 50th and 95th Percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA Latency(ms) 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_confirm-latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.5" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyA $NodeA Latency(ms) 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_confirm-latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.95" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Latency(ms) 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_confirm-latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.5" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB  Latency(ms) 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_confirm-latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.95" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Per Publisher Rates (Fairness)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Node A Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "min" }
     ]
    },
    {
     "alias": "Node A 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "50" }
     ]
    },
    {
     "alias": "Node A 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "95" }
     ]
    },
    {
     "alias": "Node B Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "min" }
     ]
    },
    {
     "alias": "Node B 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "50" }
     ]
    },
    {
     "alias": "Node B 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "95" }
     ]
    }
   ]
  },
  {
   "title": "Confirm Latency 99th and 99.9th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA Latency (ms) 99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_confirm-latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.99" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyA $NodeA Latency (ms) 99.9th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_confirm-latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.999" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Latency (ms) 99th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_confirm-latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.99" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Latency (ms) 99.9th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_confirm-latency_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.999" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Per Consumer Rates (Fairness)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Node A Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-consumer-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "min" }
     ]
    },
    {
     "alias": "Node A 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-consumer-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "50" }
     ]
    },
    {
     "alias": "Node A 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-consumer-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "95" }
     ]
    },
    {
     "alias": "Node B Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-consumer-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "min" }
     ]
    },
    {
     "alias": "Node B 50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-consumer-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "50" }
     ]
    },
    {
     "alias": "Node B 95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-consumer-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "95" }
     ]
    }
   ]
  },
  {
   "title": "Consumer Connection Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA Consumer Connection Errors (Sum in interval)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-conn-errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Consumer Connection Errors (Sum in interval)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer-conn-errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Node A Per Publisher Rates (Fairness)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "min" }
     ]
    },
    {
     "alias": "25th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "25" }
     ]
    },
    {
     "alias": "50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "50" }
     ]
    },
    {
     "alias": "75th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "75" }
     ]
    },
    {
     "alias": "95%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "95" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeA$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "max" }
     ]
    }
   ]
  },
  {
   "title": "Blocked/Unblocked Connections Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$NodeA Blocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-blocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$NodeA Unblocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-unblocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$NodeB Blocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-blocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    },
    {
     "alias": "$NodeB Unblocked Connection Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publisher-unblocked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Node B Per Publisher Rates (Fairness)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "min" }
     ]
    },
    {
     "alias": "25th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "25" }
     ]
    },
    {
     "alias": "50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "50" }
     ]
    },
    {
     "alias": "75th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "75" }
     ]
    },
    {
     "alias": "95%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "95" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_per-publisher-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$NodeB$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "max" }
     ]
    }
   ]
  },
  {
   "title": "Message Headers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA Message Headers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-headers",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Message Headers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_published-msg-headers",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Routing Key Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA Routing Key Length",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_routingkey-length",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Routing Key Length",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_routingkey-length",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  },
  {
   "title": "Delivery Mode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$TechnologyA $NodeA Delivery Mode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publish-msg-del-mode",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyA$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeA$/" }
     ]
    },
    {
     "alias": "$TechnologyB $NodeB Delivery Mode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amqp_publish-msg-del-mode",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "technology", "operator": "=~", "value": "/^$TechnologyB$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$NodeB$/" }
     ]
    }
   ]
  }
 ]
}