- hosts: "tag_inventorygroup_benchmarking_rabbitmq{{ node }}_{{ run_tag }}"
  remote_user: ubuntu
  become: yes
  vars_files:
    # change to location of var files
    - .variables/telegraf-vars.yml
  roles:
    - preliminary
    - rabbitmq
    - telegraf