kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: st1
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: st1
  fsType: xfs 